### ISSUE TITLE
near validators current not showing my pool, but debug does.

### ISSUE THREAD

**Issue by stakefarm** [near/stakewars-iii#121]
![image](https://user-images.githubusercontent.com/71701221/185886983-b827e884-b072-4108-89e9-928da9812550.png)
![image](https://user-images.githubusercontent.com/71701221/185885390-521025c0-b12a-48f4-8d66-404fe3edfc97.png)
![image](https://user-images.githubusercontent.com/71701221/185885514-c5ebdbdc-d8e7-421e-8615-157135ae7dce.png)
![image](https://user-images.githubusercontent.com/71701221/185885628-25b5697f-3e23-47cb-b886-38163637dd77.png)

All images above are from current epoch (except for proposal accepted, which was from epoch before), I think I'm validating, but not showing up in near validators current. I refreshed my debug browser twice to be sure.

**Comment by joesixpack** [comment]
This is not a debug, debug shows the next epoch before its reached.  You probably just got kicked out.

**Comment by stakefarm** [comment]
I had a proposal accepted for 2,491. The next epoch I wasn't shown in the list, but seat price was 2,465. My uptime has consistently been 95-100%. 
Here is more recent debug screenshot. 
![image](https://user-images.githubusercontent.com/71701221/186025266-8c683a46-9d1c-458b-820a-5492831393eb.png)
