### ISSUE TITLE
New participants cannot assess shardnet wallet

### ISSUE THREAD

**Issue by ndtam0785** [near/stakewars-iii#123]
Dear team,

**From my view as a new participant, my experience for near shardnet is bad compared to other blockchain testnet. At least, they let me know that I cannot join. Not joining already, and the team said no, it's too late.**

**Why didn't you just announce that no new participants is allowed. If you announced that, I'd had never joined your program. Now when I'm ready to join, hire VPS, spend time,... just learn that I'm not allowed to join.** 

**How can new participants join if the shardnet wallet did not work. Why didn't you just let new comers that we cannot join?
Please read below for more details.

I'm just joining NEAR stakewar III. I was creating shardnet wallet, but I could not assess the wallet by passphrase. I was going to discord for help, and the others in discord said their wallet was loading. And here the team member said:

![image](https://user-images.githubusercontent.com/111944036/186314159-b45b5a11-338f-44e9-92d9-09fff20a53dd.png)

![image](https://user-images.githubusercontent.com/111944036/186312810-c585a8e2-b7ad-43f6-9e4b-0c358e6bd5be.png)

I was feeling weird a bit. Before joining I have read through the rules carefully, and I learnt that **new participants are welcome to join at any time, just be sure to have time to fulfil the challenges. And I read that the due date for all challenges is Sep 7, which is 2 weeks ahead.** 

![image](https://user-images.githubusercontent.com/111944036/186314726-72e09a23-2144-4373-863c-fe3f4299afa5.png)

![image](https://user-images.githubusercontent.com/111944036/186315641-a638354f-fb6d-446f-b3d6-00a2f0b660df.png)

**Comment by DDeAlmeida** [comment]
This was an early unofficial announcement as i said, wait official Announcement.

**Comment by ndtam0785** [comment]
I do hope you announce it officially sooner :) Thanks!
