### ISSUE TITLE
Problem with config.json file

### ISSUE THREAD

**Issue by cristian-cloudmex** [near/stakewars-iii#17]
The property "archive" is set as false in the config.json file downloaded from S3 bucket

<img width="133" alt="Captura de Pantalla 2022-07-15 a la(s) 19 59 31" src="https://user-images.githubusercontent.com/49256708/179334390-0b556c38-1dcc-4bb1-9538-d54d724e7a92.png">

<img width="1110" alt="Captura de Pantalla 2022-07-15 a la(s) 20 00 31" src="https://user-images.githubusercontent.com/49256708/179334421-77f19028-6023-44bd-ad5a-9904444291d5.png">

**Comment by EdwardsVO** [comment]
yes, it is needed to run `sed -e 's/"archive": false/"archive": true/' -i config.json` for setting to `True` this attribute

**Comment by DDeAlmeida** [comment]
Closed, OSA Shared Archival Snapshot and NoArchival Snapshot.
With HardFork, this is done, only noarchival is available
