### ISSUE TITLE
Stake Wars: Episode III. Challenge 005 article

### ISSUE THREAD

**Issue by CodingJzy** [near/stakewars-iii#18]
I have sorted out the process of my deployment in AWS. Please have a look, thank you：
[AWS-DEPLOY-ARTICLE](https://github.com/CodingJzy/stakewars)
😄

**Comment by EdwardsVO** [comment]
Good article friend ! The last dashboard image is yours ? What are you using ? Looks great

**Comment by CodingJzy** [comment]
thx， :smile:  Dashboard is Prometheus and grafana

**Comment by DDeAlmeida** [comment]
Fill form, not issue form Challenge submissions ;)
https://docs.google.com/forms/d/e/1FAIpQLScp9JEtpk1Fe2P9XMaS9Gl6kl9gcGVEp3A5vPdEgxkHx3ABjg/viewform

**Comment by CodingJzy** [comment]
ok, thx
