### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by dwrx** [near/stakewars-iii#22]
When I started node 2 days ago the mem usage was ~ 1 gb, now it sits at 3.5 gb. Looks like there is some memory leak in the node software, or it's expected due to increased amount of nodes?

**Comment by nikurt** [comment]
shardnet and betanet and test have similar RAM usage patterns. See below.

As chunk-only-producers are enabled in both shardnet and betanet, comparing these two doesn't help.
testnet doesn't yet have chunk-only-producers but behaves similarly to the other two networks.

3.5GB RAM is not too much, as minimal hardware requirements are 8GB RAM.

Based on the RAM usage graphs of different networks, I don't see an obvious memory leak. Some increase in RAM usage over the process' lifetime is normal.

shardnet RAM usage:
![image](https://user-images.githubusercontent.com/86772482/180208388-6e39430b-e022-4fcd-8ece-fb251101c70c.png)

betanet RAM usage: 
![image](https://user-images.githubusercontent.com/86772482/180208641-21598691-4607-4739-8304-c21b88ac5429.png)

testnet RAM usage: 
![image](https://user-images.githubusercontent.com/86772482/180209016-954eb964-b13b-4338-b6a5-6e83c9453c79.png)
