### ISSUE TITLE
registration form and rule number 3

### ISSUE THREAD

**Issue by jambulmerah** [near/stakewars-iii#40]
Hello sir, what is meant about rule number 3?
Can you explain in more detail about rule number 3 below?🙏🙏🙏

![Screenshot_20220724-070406_Chrome-picsay](https://user-images.githubusercontent.com/103844658/180627342-bb9246ea-26a2-4a2e-9468-70e33a9d5483.jpg)

and what should I fill in this part of the form?
does it ask for mainnet or shardnet ID?

![Screenshot_20220724-070559_Chrome](https://user-images.githubusercontent.com/103844658/180627475-aa35c1d0-ba5e-43c7-8ed1-5ed5ea93baa2.jpg)

Please clear my confusion here with your replies and answers.

Thanks you🙏🙏🙏

**Comment by DDeAlmeida** [comment]
Fill email or mainnet wallet.

Mandatory Form is https://docs.google.com/forms/d/e/1FAIpQLScp9JEtpk1Fe2P9XMaS9Gl6kl9gcGVEp3A5vPdEgxkHx3ABjg/viewform for getting rewards
