### ISSUE TITLE
Shardnet Tag

### ISSUE THREAD

**Issue by joesixpack** [near/stakewars-iii#56]
re: https://discord.com/channels/490367152054992913/999047336229617704/1002241756387082300

Does not match what is in commit.md, so its dangerous to use.

**Comment by joesixpack** [comment]
![image](https://user-images.githubusercontent.com/23145642/181805743-fb61bcc5-8d37-4d01-8f12-8a3dba7cd507.png)

**Comment by posvyatokum** [comment]
It looks like your tag list wasn't updated. Try to fetch all tags again. You'll need to do that after every commit update.

**Comment by joesixpack** [comment]
All good!

![image](https://user-images.githubusercontent.com/23145642/182285735-7845c311-1232-4329-81f0-1407236fc3dd.png)
