### ISSUE TITLE
Challenge 8 - Withdraw Rewards

### ISSUE THREAD

**Issue by joesixpack** [near/stakewars-iii#58]
Appears to be a bug with this contract call.  Instead of just distributing the rewards (and it appears to have missed the second wallet also), it seems to unstake the entire validator stake and the validator disappears.  Had to restake with fresh tokens above the minimum balance and ping to get it back into proposals.

![challenge8](https://user-images.githubusercontent.com/23145642/181803218-5650d9eb-954e-4e94-b5a9-14ceccfb57e9.png)

https://explorer.shardnet.near.org/transactions/Ge6baSvv7JrLmZERqRjec65ybYSUxmrXSzuxMVbt3nsY

**Comment by joesixpack** [comment]
I was stupid and tried it again, clearly it should not be unstaking the pool?

![image](https://user-images.githubusercontent.com/23145642/182037162-79ad5a73-4bc3-4f67-892d-56275a2d940a.png)

**Comment by joetan79** [comment]
I also having the same problem. After run this contract and it's withdraw all my staking as well as validators has been kicked out

**Comment by joesixpack** [comment]
https://github.com/zavodil/near-staking-pool-owner/issues/2#issue-1326104703

**Comment by Foo115** [comment]
Im having same issue, i think there is some bug on the contract. 
Had change the numerator and denomirator also to low as possible but still gettin unstaking all balance on pool

**Comment by ivanguardia** [comment]
I had the same. I lost 4 epochs -> unstake all, get rewards, stake all, ping, and finally set active again.
The withdrawal should be only the reward and not all the staking available.
This is a smartcontract issue.

**Comment by stiavnik** [comment]
Yes, as part of the challenge I submitted where exactly the error in code is, on the other side I may be wrong because I don't really know Rust yet. Remember the challenge asks as to report if something goes wrong, so...?

**Comment by onsails** [comment]
Apparently I have the same issue with validator which was in active set and with brand new validator #114

**Comment by ShaMate256** [comment]
The same for me It unstaked all.

Use **near call pool_id stake_all --accountId account** to return stake back.
