### ISSUE TITLE
When I enter the name of the wallet. the console dies. And nothing happens.

### ISSUE THREAD

**Issue by miinimes1** [near/stakewars-iii#75]
![image](https://user-images.githubusercontent.com/110528747/182564134-b97eb570-babe-44c1-bf2d-b7e02e9e611d.png)

**Comment by deden2904** [comment]
the solution I just blocked the link, didn't press ctrl+c

**Comment by miinimes1** [comment]
> the solution I just block the link, didn't press ctrl+c
I didn't open the link. I just entered my wallet name. Nothing happened.
![image](https://user-images.githubusercontent.com/110528747/182572589-6c389fc9-bb62-424a-8488-15ee772d6a1f.png)

**Comment by kiskesis** [comment]
When you copy the link and past account don't use ctrl + c and ctrl +v, just use your mouse.

**Comment by miinimes1** [comment]
> When you copy the link and past account don't use ctrl + c and ctrl +v, just use your mouse.

I'm shocked. it worked. Looool. Just lol. Thanks so much guys.
