### ISSUE TITLE
Local RPC Timing Out

### ISSUE THREAD

**Issue by joesixpack** [near/stakewars-iii#79]
Starting to see this issue crop up on more powerful machines, not just low end.

![image](https://user-images.githubusercontent.com/23145642/182730211-349c25a2-927b-4af9-b71a-315023cd8f34.png)

**Comment by DDeAlmeida** [comment]
Port 3030 is open ?

**Comment by joesixpack** [comment]
Yeah, but I think the build was running continously because the boot nodes were updated before the commit.
