### ISSUE TITLE
Problem with the crontab

### ISSUE THREAD

**Issue by miinimes1** [near/stakewars-iii#91]
I have set up a cron task. The ping transaction doesn't show up. I created a file called ping.sh. The path is correct. Please. Can you please tell me what I can try to do?

**Comment by DDeAlmeida** [comment]
Add screeshot please

**Comment by ivanguardia** [comment]
Likely a path problem or relative directories.

**Comment by miinimes1** [comment]
I found where I made a mistake. I'm sorry to have disturbed you. Please close the thread. It's working now!
