### ISSUE TITLE
Blockchain sync has stuck

### ISSUE THREAD

**Issue by dwrx** [near/stakewars-iii#95]
```
INFO stats: # 1438750 Downloading blocks 4.16% (461236 left; at 1438750) 29 peers ⬇ 4.07 MB/s ⬆ 6.81 MB/s 0.00 bps 0 gas/s CPU: 59%, Mem: 7.81 GB
INFO stats: # 1438750 Downloading blocks 4.16% (461239 left; at 1438750) 30 peers ⬇ 4.00 MB/s ⬆ 12.0 MB/s 0.00 bps 0 gas/s CPU: 56%, Mem: 8.32 GB
INFO stats: # 1438750 Downloading blocks 4.16% (461243 left; at 1438750) 30 peers ⬇ 4.29 MB/s ⬆ 11.9 MB/s 0.00 bps 0 gas/s CPU: 45%, Mem: 7.38 GB
INFO stats: # 1438750 Downloading blocks 4.16% (461246 left; at 1438750) 30 peers ⬇ 4.14 MB/s ⬆ 6.58 MB/s 0.00 bps 0 gas/s CPU: 48%, Mem: 7.69 GB
INFO stats: # 1438750 Downloading blocks 4.16% (461251 left; at 1438750) 30 peers ⬇ 4.47 MB/s ⬆ 11.9 MB/s 0.00 bps 0 gas/s CPU: 66%, Mem: 8.31 GB
```
After the restart of the `neard` service:
```
WARN sync: Block sync: 1438750/1900059 No available archival peers to request block
....
```
HEAD detached at 68bfa84ed
Tried to delete blockchain and resync from scratch.

**Comment by stiavnik** [comment]
I had similar when I purposely tried "archive true" in config.json, but "official" from S3 wget is set like this:

`"archive": false`

(ignore if this is something else)

**Comment by dwrx** [comment]
Thanks @stiavnik i will try to re-sync with non archival config (unfortunately, you need to delete `data` and re-start sync process). In the past it was required to switch node to archival mode, so I did it as usual during migration from the forked chain.

**Comment by dwrx** [comment]
> I had similar when I purposely tried "archive true" in config.json, but "official" from S3 wget is set like this:
> 
> `"archive": false`

I confirm that resync after setting archive to `false` worked for me. Looks like there is no more archival nodes. 
Thanks @stiavnik
