### ISSUE TITLE
Observations: Node failed to catch up after adding network.public_addrs

### ISSUE THREAD

**Issue by Thesephi** [near/stakewars-iii#98]
So.. my node was working well for the entire day (good uptime, normal CPU usage).

Then I got the announcement to add `network.public_addrs` to the config, which I did.

# ISSUE 1

After restarting the node, I noticed this in the log:
```
encountered unrecognised field: network.public_addrs
```

So it looked like the node didn't understand the config. I'm sure there's no typo as I copied & pasted directly from the instruction. It's the literal string `public_addrs`

# ISSUE 2

After restarting the node, I expected that it'd take maximum a minute for the node to catch up & continue validating.. But I was wrong and/or very unlucky. My node never caught up afterwards:

![node-fails-to-catchup](https://user-images.githubusercontent.com/2597375/184270392-90f7a693-d9b5-4bd2-8fce-96eb37f16657.png)

I tried restarting several times. Took me hours of waiting in vain. My node is falling behind more and more.

My naive thinking is that this could have been a poor network state. But it could have been something else, as I notice these kinds of logs quite often:

![mailbox-closed](https://user-images.githubusercontent.com/2597375/184270731-c1fe7a15-44ed-4f52-9121-811738ad97a8.png)

and

![connectionreset](https://user-images.githubusercontent.com/2597375/184270926-480f9e94-1984-40d5-a55f-46a1c89695b7.png)

Hope this issue helps shed some light or trigger some useful discussions 🙂

Thanks all!

**Comment by Thesephi** [comment]
After several discussions, I decided to upgrade storage speed, and things worked well since then. I'm still curious why it worked okay before, and only became an issue recently. Anyhow, if it works, it works :)

Issue 1 (the node doesn't seem to recognize the `public_addrs` config option) remains to be discussed (imho).

**Comment by joesixpack** [comment]
Use the latest commit and it will recognize it.

**Comment by Thesephi** [comment]
Confirmed that the issue about `public_addrs` not being recognized, has been resolved in a more recent release commit. Closing issue. Thank you for the insight above!
